name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23li2kELnSv0fELM4V"
GITHUB_OWNER = "lickyzh"
GITHUB_REPO = "NavSite"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navsite.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://navsite.pages.dev"

